version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/volume/rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/volume/rabbitmq/log/:/var/log/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always
